FROM resin/%%BALENA_MACHINE_NAME%%-node:8

WORKDIR /usr/src/app

COPY trui-pi/ .

RUN apt-get update
RUN sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev
RUN npm install

CMD ["node", "app.js"]
